=== dswarm/dswarm/converter/src/test/resources/MARC21slim.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.loc.gov/MARC21/slim" xmlns="http://www.loc.gov/MARC21/slim" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1" xml:lang="en">
  <xsd:annotation>
    <xsd:documentation>
			MARCXML: The MARC 21 XML Schema
			Prepared by Corey Keith
			
				May 21, 2002 - Version 1.0  - Initial Release

**********************************************
Changes.

August 4, 2003 - Version 1.1 - 
Removed import of xml namespace and the use of xml:space="preserve" attributes on the leader and controlfields. 
                    Whitespace preservation in these subfields is accomplished by the use of xsd:whiteSpace value="preserve"

May 21, 2009  - Version 1.2 - 
in subfieldcodeDataType  the pattern 
                          "[\da-z!"#$%&amp;'()*+,-./:;&lt;=&gt;?{}_^`~\[\]\\]{1}"
	changed to:	
                         "[\dA-Za-z!"#$%&amp;'()*+,-./:;&lt;=&gt;?{}_^`~\[\]\\]{1}"
    i.e "A-Z" added after "[\d" before "a-z"  to allow upper case.  This change is for consistency with the documentation.
	
************************************************************
			This schema supports XML markup of MARC21 records as specified in the MARC documentation (see www.loc.gov).  It allows tags with
			alphabetics and subfield codes that are symbols, neither of which are as yet used in  the MARC 21 communications formats, but are 
			allowed by MARC 21 for local data.  The schema accommodates all types of MARC 21 records: bibliographic, holdings, bibliographic 
			with embedded holdings, authority, classification, and community information.
		</xsd:documentation>
  </xsd:annotation>
  <xsd:element name="record" type="recordType" nillable="true" id="record.e">
    <xsd:annotation>
      <xsd:documentation>record is a top level container element for all of the field elements which compose the record</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name="collection" type="collectionType" nillable="true" id="collection.e">
    <xsd:annotation>
      <xsd:documentation>collection is a top level container element for 0 or many records</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:complexType name="collectionType" id="collection.ct">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="record"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="idDataType" use="optional"/>
  </xsd:complexType>
  <xsd:complexType name="recordType" id="record.ct">
    <xsd:sequence minOccurs="0">
      <xsd:element name="leader" type="leaderFieldType"/>
      <xsd:element name="controlfield" type="controlFieldType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="datafield" type="dataFieldType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="recordTypeType" use="optional"/>
    <xsd:attribute name="id" type="idDataType" use="optional"/>
  </xsd:complexType>
  <xsd:simpleType name="recordTypeType" id="type.st">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="Bibliographic"/>
      <xsd:enumeration value="Authority"/>
      <xsd:enumeration value="Holdings"/>
      <xsd:enumeration value="Classification"/>
      <xsd:enumeration value="Community"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="leaderFieldType" id="leader.ct">
    <xsd:annotation>
      <xsd:documentation>MARC21 Leader, 24 bytes</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleContent>
      <xsd:extension base="leaderDataType">
        <xsd:attribute name="id" type="idDataType" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:simpleType name="leaderDataType" id="leader.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
      <xsd:pattern value="[\d ]{5}[\dA-Za-z ]{1}[\dA-Za-z]{1}[\dA-Za-z ]{3}(2| )(2| )[\d ]{5}[\dA-Za-z ]{3}(4500|    )"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="controlFieldType" id="controlfield.ct">
    <xsd:annotation>
      <xsd:documentation>MARC21 Fields 001-009</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleContent>
      <xsd:extension base="controlDataType">
        <xsd:attribute name="id" type="idDataType" use="optional"/>
        <xsd:attribute name="tag" type="controltagDataType" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:simpleType name="controlDataType" id="controlfield.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="controltagDataType" id="controltag.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
      <xsd:pattern value="00[1-9A-Za-z]{1}"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="dataFieldType" id="datafield.ct">
    <xsd:annotation>
      <xsd:documentation>MARC21 Variable Data Fields 010-999</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="subfield" type="subfieldatafieldType"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="idDataType" use="optional"/>
    <xsd:attribute name="tag" type="tagDataType" use="required"/>
    <xsd:attribute name="ind1" type="indicatorDataType" use="required"/>
    <xsd:attribute name="ind2" type="indicatorDataType" use="required"/>
  </xsd:complexType>
  <xsd:simpleType name="tagDataType" id="tag.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
      <xsd:pattern value="(0([1-9A-Z][0-9A-Z])|0([1-9a-z][0-9a-z]))|(([1-9A-Z][0-9A-Z]{2})|([1-9a-z][0-9a-z]{2}))"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="indicatorDataType" id="ind.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
      <xsd:pattern value="[\da-z ]{1}"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="subfieldatafieldType" id="subfield.ct">
    <xsd:simpleContent>
      <xsd:extension base="subfieldDataType">
        <xsd:attribute name="id" type="idDataType" use="optional"/>
        <xsd:attribute name="code" type="subfieldcodeDataType" use="required"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:simpleType name="subfieldDataType" id="subfield.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="subfieldcodeDataType" id="code.st">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="preserve"/>
      <xsd:pattern value="[\dA-Za-z!&quot;#$%&amp;'()*+,-./:;&lt;=&gt;?{}_^`~\[\]\\]{1}"/>
      <!-- "A-Z" added after "\d" May 21, 2009 -->
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="idDataType" id="id.st">
    <xsd:restriction base="xsd:ID"/>
  </xsd:simpleType>
</xsd:schema>

=== dswarm/dswarm/controller/src/main/resources/DD-134/marcxml_test_record.xml
<?xml version = "1.0" encoding = "UTF-8"?>
  <collection xmlns="http://www.loc.gov/MARC21/slim"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.loc.gov/MARC21/slim
http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
    <record xmlns="http://www.loc.gov/MARC21/slim"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.loc.gov/MARC21/slim
http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
      <leader>     nam  2200457 a 4500</leader>
      <controlfield tag="001">003404590</controlfield>
      <controlfield tag="005">20091106150915.0</controlfield>
      <controlfield tag="006">m        d</controlfield>
      <controlfield tag="007">cr bn|||||||||</controlfield>
      <controlfield tag="008">091028s2008    caua          000 p eng d</controlfield>
      <datafield tag="024" ind1="8" ind2=" ">
        <subfield code="a">21085</subfield>
      </datafield>
      <datafield tag="024" ind1="8" ind2=" ">
        <subfield code="a">3.84</subfield>
      </datafield>
      <datafield tag="024" ind1="8" ind2=" ">
        <subfield code="a">R219235</subfield>
      </datafield>
      <datafield tag="035" ind1=" " ind2=" ">
        <subfield code="a">(OCoLC)ocn460736493</subfield>
      </datafield>
      <datafield tag="040" ind1=" " ind2=" ">
        <subfield code="a">CUT</subfield>
        <subfield code="c">CUT</subfield>
      </datafield>
      <datafield tag="245" ind1="0" ind2="4">
        <subfield code="a">The bonny scot</subfield>
        <subfield code="h">[electronic resource] :</subfield>
        <subfield code="b">or, the yielding lass.</subfield>
      </datafield>
      <datafield tag="246" ind1="1" ind2=" ">
        <subfield code="i">First line:</subfield>
        <subfield code="a">AS I sate at my Spinning=Wheel</subfield>
      </datafield>
      <datafield tag="260" ind1=" " ind2=" ">
        <subfield code="a">Santa Barbara, CA :</subfield>
        <subfield code="b">University of California, Santa Barbara, The Early Modern Center,</subfield>
        <subfield code="c">2008.</subfield>
      </datafield>
      <datafield tag="516" ind1=" " ind2=" ">
        <subfield code="a">Text (XML).</subfield>
      </datafield>
      <datafield tag="538" ind1=" " ind2=" ">
        <subfield code="a">System requirements: Web browser for the XML and HTML files.</subfield>
      </datafield>
      <datafield tag="538" ind1=" " ind2=" ">
        <subfield code="a">Mode of access: Internet; host: ebba.english.ucsb.edu.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">Title from English Broadside Ballad Archive (queried 2008 Nov 07).</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">Original Publication Date: c. 1664-1696.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">TEI file encoded by the English Broadside Ballad Archive Editorial Team.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">EMC no. 21085.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">Pepys 3.84.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">ESTC no. R219235.</subfield>
      </datafield>
      <datafield tag="500" ind1=" " ind2=" ">
        <subfield code="a">Reference: Wing B3604[B]; Rollins (2) ?222 (March 1, 1675, ii, 499).</subfield>
      </datafield>
      <datafield tag="534" ind1=" " ind2=" ">
        <subfield code="p">Reproduction of Microfilm :</subfield>
        <subfield code="a">Magdalene College (University of Cambridge).</subfield>
        <subfield code="t">The Pepys ballads</subfield>
        <subfield code="c">Cambridge [England] : The Pepys Library, Magdalene College, 2003.</subfield>
      </datafield>
      <datafield tag="536" ind1=" " ind2=" ">
        <subfield code="a">Sponsored by the University of California, Santa Barbara and The Early Modern Center.</subfield>
      </datafield>
      <datafield tag="540" ind1=" " ind2=" ">
        <subfield code="a">The University of California makes a claim of copyright only to original contributions made by Early Modern Center participants and other members of the university community. The University of California makes no claim of copyright to the original text. Permission is granted to download, transmit or otherwise reproduce, distribute or display the contributions to this work claimed by The University of California for non-profit educational purposes, provided that this header is included in its entirety. For inquiries about commercial uses, please contact: Early Modern Center - English Department, University of California, Santa Barbara, CA 93105, United States of America, Email: http://ebba.english.ucsb.edu/contact/.</subfield>
      </datafield>
      <datafield tag="650" ind1=" " ind2="0">
        <subfield code="a">Ballads, English</subfield>
        <subfield code="y">17th century.</subfield>
      </datafield>
      <datafield tag="650" ind1=" " ind2="0">
        <subfield code="a">Broadside</subfield>
        <subfield code="y">17th century.</subfield>
      </datafield>
      <datafield tag="655" ind1=" " ind2="7">
        <subfield code="a">Ballads</subfield>
        <subfield code="2">aat</subfield>
      </datafield>
      <datafield tag="710" ind1="2" ind2=" ">
        <subfield code="a">University of California, Santa Barbara.</subfield>
        <subfield code="b">Early Modern Center.</subfield>
      </datafield>
      <datafield tag="740" ind1="0" ind2=" ">
        <subfield code="a">English Broadside Ballad Archive.</subfield>
      </datafield>
      <datafield tag="856" ind1="4" ind2="0">
        <subfield code="u">http://ebba.english.ucsb.edu/ballad/21085/</subfield>
        <subfield code="z">English Broadside Ballad Archive.</subfield>
      </datafield>
      <datafield tag="049" ind1=" " ind2=" ">
        <subfield code="a">CUTM</subfield>
      </datafield>
    </record>

</collection>
