=== dswarm/dswarm/controller/src/main/resources/mabxml-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--		
		MABxml - Level  1
		
		version: 1.2		
		date: 2004-05-04 
		description: Einfaches XML Schema zur Abbildung eines MAB2-Satzes auf XML. 
		author: JÃ¼rgen Kett, Deutsche Nationalbibliothek
		identifier: http://www.ddb.de/professionell/mabxml/mabxml-1.xsd 
			
-->
<xsd:schema targetNamespace="http://www.ddb.de/professionell/mabxml/mabxml-1.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ddb.de/professionell/mabxml/mabxml-1.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1" xml:lang="de">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
	<!-- elements: -->
	<xsd:element name="datei" type="dateiType" nillable="true" id="datei.e">
		<xsd:annotation>
			<xsd:documentation>Wurzelelement einer Sammlung von MABXML-DatensÃ¤tzen</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:element name="datensatz" type="datensatzType" nillable="true" id="datensatz.e">
		<xsd:annotation>
			<xsd:documentation>Wurzelelement eines jeden MABXML Datensatzes. </xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<!-- element types: -->
	<xsd:complexType name="dateiType" id="datei.ct">
		<xsd:annotation>
			<xsd:documentation>Typ Datei</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element ref="datensatz"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="idType" use="optional"/>
		<xsd:attribute name="typ" type="dateitypType" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="datensatzType" id="datensatz.ct">
		<xsd:annotation>
			<xsd:documentation>Typ Datensatz</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="feld" type="feldType" id="feld.e">
				<xsd:annotation>
					<xsd:documentation>Standard MAB-Feld</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="idType" use="optional"/>
		<xsd:attribute name="typ" type="satztypType" use="required"/>
		<xsd:attribute name="status" type="satzstatusType" use="required"/>
		<xsd:attribute name="mabVersion" type="mabVersionType" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="feldType" id="feld.ct" mixed="true">
		<xsd:annotation>
			<xsd:documentation>Typ Feld</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:group ref="basisElemente" minOccurs="0"/>
			<xsd:element name="uf" type="ufType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Unterfeld</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="idType" use="optional"/>
		<xsd:attribute name="nr" type="feldnummerType" use="required"/>
		<xsd:attribute name="ind" type="indikatorType" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ufType" id="uf.st" mixed="true">
		<xsd:annotation>
			<xsd:documentation>Typ Unterfeld</xsd:documentation>
		</xsd:annotation>
		<xsd:group ref="basisElemente" minOccurs="0" maxOccurs="unbounded"/>
		<xsd:attribute name="id" type="idType" use="optional"/>
		<xsd:attribute name="code" type="codeType" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="nsType" id="ns.st">
		<xsd:annotation>
			<xsd:documentation>Typ Nicht-Sortieren</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:whiteSpace value="collapse"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="stwType" id="stw.st">
		<xsd:annotation>
			<xsd:documentation>Typ Stichwort</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:whiteSpace value="collapse"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="tfType" id="tf.ct">
		<xsd:annotation>
			<xsd:documentation>Typ Teilfeld</xsd:documentation>
		</xsd:annotation>
	</xsd:complexType>
	<xsd:group name="basisElemente">
		<xsd:annotation>
			<xsd:documentation>Gruppe Basiselemente</xsd:documentation>
		</xsd:annotation>
		<xsd:choice>
			<xsd:element name="tf" type="tfType">
				<xsd:annotation>
					<xsd:documentation>Teilfeld</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="stw" type="stwType">
				<xsd:annotation>
					<xsd:documentation>Stichwort</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ns" type="nsType">
				<xsd:annotation>
					<xsd:documentation>Nicht-Sortieren</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:choice>
	</xsd:group>
	<!-- attribute types: -->
	<xsd:simpleType name="feldnummerType" id="feldnummer.st">
		<xsd:annotation>
			<xsd:documentation>Typ Feldnummer</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:minInclusive value="001" fixed="false"/>
			<xsd:maxInclusive value="999" fixed="false"/>
			<xsd:pattern value="[0-9][0-9][0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="indikatorType" id="indikator.st">
		<xsd:annotation>
			<xsd:documentation>Typ Feldindikator</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-z]"/>
			<xsd:pattern value="\s"/>
			<xsd:pattern value="[0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="codeType" id="code.st">
		<xsd:annotation>
			<xsd:documentation>Typ Unterfeldcode</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="dateitypType" id="dateityp.st">
		<xsd:annotation>
			<xsd:documentation>Typ Dateityp</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="TITEL"/>
			<xsd:enumeration value="PND"/>
			<xsd:enumeration value="GKD"/>
			<xsd:enumeration value="SWD"/>
			<xsd:enumeration value="NOTAT"/>
			<xsd:enumeration value="LOKAL"/>
			<xsd:enumeration value="ADRESS"/>
			<xsd:enumeration value="REDAKTION"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="satzstatusType" id="satzstatus.st">
		<xsd:annotation>
			<xsd:documentation>Typ Satzstatus (Satzkennung)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="c"/>
			<xsd:enumeration value="d"/>
			<xsd:enumeration value="n"/>
			<xsd:enumeration value="p"/>
			<xsd:enumeration value="u"/>
			<xsd:enumeration value="v"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="satztypType" id="satztyp.st">
		<xsd:annotation>
			<xsd:documentation>Typ Satztyp (Satzkennung)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="h"/>
			<xsd:enumeration value="y"/>
			<xsd:enumeration value="u"/>
			<xsd:enumeration value="v"/>
			<xsd:enumeration value="p"/>
			<xsd:enumeration value="t"/>
			<xsd:enumeration value="k"/>
			<xsd:enumeration value="w"/>
			<xsd:enumeration value="r"/>
			<xsd:enumeration value="s"/>
			<xsd:enumeration value="x"/>
			<xsd:enumeration value="q"/>
			<xsd:enumeration value="l"/>
			<xsd:enumeration value="e"/>
			<xsd:enumeration value="m"/>
			<xsd:enumeration value="c"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="mabVersionType" id="mabVersion.st">
		<xsd:annotation>
			<xsd:documentation>Typ MAB-Version (Satzkennung)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="M2.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="idType" id="id.st">
		<xsd:annotation>
			<xsd:documentation>Typ id</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:ID"/>
	</xsd:simpleType>
</xsd:schema>

=== dswarm/dswarm/controller/src/main/resources/DD-134/test-mabxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<datei xmlns="http://www.ddb.de/professionell/mabxml/mabxml-1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://files.dnb.de/standards/formate/mabxml-1.xsd">
    <datensatz typ="h" status="n" mabVersion="M2.0">
        <feld nr="001" ind=" ">06978834</feld>
        <feld nr="002" ind="a">19981028</feld>
        <feld nr="003" ind=" ">20010620</feld>
        <feld nr="005" ind="n">20011121</feld>
        <feld nr="029" ind="m">MB</feld>
        <feld nr="030" ind=" ">az1dcr|||||37</feld>
        <feld nr="037" ind="z">dt.</feld>
        <feld nr="050" ind=" ">|||||c||||||||</feld>
        <feld nr="051" ind=" ">n||||||</feld>
        <feld nr="070" ind=" ">KNUB</feld>
        <feld nr="070" ind="b">FRhk</feld>
        <feld nr="076" ind="n">098301</feld>
        <feld nr="076" ind="k">101171</feld>
        <feld nr="076" ind="v">5</feld>
        <feld nr="077" ind="p">00872805<tf/>Roll, Gernot</feld>
        <feld nr="077" ind="p">00872284<tf/>Thomas, Eugen</feld>
        <feld nr="100" ind="b">Wirth, Franz Peter</feld>
        <feld nr="102" ind=" ">00412254</feld>
        <feld nr="104" ind="b">Mann, Golo</feld>
        <feld nr="106" ind=" ">00243077</feld>
        <feld nr="108" ind="b">Ahlsen, Leopold</feld>
        <feld nr="110" ind=" ">00004514</feld>
        <feld nr="112" ind="b">Boysen, Rolf</feld>
        <feld nr="114" ind=" ">00045374</feld>
        <feld nr="116" ind="b">Pekny, Romuald</feld>
        <feld nr="118" ind=" ">00465696</feld>
        <feld nr="120" ind="b">Kreindl, Werner</feld>
        <feld nr="122" ind=" ">00209123</feld>
        <feld nr="331" ind=" ">Wallenstein</feld>
        <feld nr="334" ind=" ">Bildtonträger</feld>
        <feld nr="335" ind=" ">nach der Biographie von Golo Mann für das Fernsehen erzählt von Leopold Ahlsen</feld>
        <feld nr="359" ind=" ">[Darsteller:] Rolf Boysen, Romuald Pekny, Werner Kreindl ... Kamera: Gernot Roll ... Musik: Eugen Thomas. Regie: Franz Peter Wirth</feld>
        <feld nr="410" ind=" ">[Mainz]</feld>
        <feld nr="412" ind=" ">ZDF [u.a.]</feld>
        <feld nr="433" ind=" ">Videokassetten</feld>
        <feld nr="501" ind=" ">Fernsehfilm, BRD 1978</feld>
    </datensatz>

</datei>

=== dswarm/dswarm/controller/src/test/resources/test-mabxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<datei xmlns="http://www.ddb.de/professionell/mabxml/mabxml-1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ddb.de/professionell/mabxml/mabxml-1.xsd
http://www.ddb.de/professionell/mabxml/mabxml-1.xsd">
	<datensatz id="ID946451494" typ="h" status="n" mabVersion="M2.0">
		<feld nr="001" ind=" ">946451494</feld>
		<feld nr="004" ind=" ">19980605</feld>
		<feld nr="030" ind=" ">a|1iar|z|||37</feld>
		<feld nr="036" ind="a">DE</feld>
		<feld nr="050" ind=" ">a|a|||||||||||</feld>
		<feld nr="051" ind=" ">m|||z||</feld>
		<feld nr="070" ind="a">292</feld>
		<feld nr="100" ind="b">Ginsbach, Julia</feld>
		<feld nr="102" ind="a">11547577X</feld>
		<feld nr="104" ind="b">Liebers, Andrea</feld>
		<feld nr="106" ind="a">111570204</feld>
		<feld nr="331" ind=" "><ns>Die</ns> schÃ¶ne Lau</feld>
		<feld nr="335" ind=" ">nach dem Stuttgarter HutzelmÃ¤nnlein von Eduart MÃ¶rike</feld>
		<feld nr="359" ind=" ">Julia Ginsbach (Bilder) ; Andrea Liebers (Text)</feld>
		<feld nr="410" ind=" ">Leinfelden-Echterdingen</feld>
		<feld nr="412" ind=" ">DRW-Verl. Weinbrenner</feld>
		<feld nr="425" ind=" ">1995</feld>
		<feld nr="425" ind="a">1995</feld>
		<feld nr="433" ind=" ">[28] S.</feld>
		<feld nr="434" ind=" ">Ã¼berw. Ill.</feld>
		<feld nr="435" ind=" ">27 cm</feld>
		<feld nr="540" ind="a">ISBN 3-87181-371-0 Pp. : DM 24.80</feld>
		<feld nr="544" ind="a">DBL<tf/>1996 B 2108</feld>
		<feld nr="544" ind="a">DBF<tf/>1996 B 2108</feld>
		<feld nr="574" ind=" ">96,A07,0146</feld>
		<feld nr="700" ind=" ">|07</feld>
		<feld nr="800" ind=" ">118583107           MÃ¶rike, Eduard</feld>
		<feld nr="805" ind="b"><ns>Das</ns> Stuttgarter HutzelmÃ¤nnchen</feld>
	</datensatz>
</datei>
